### PR TITLE
fail if more than one of the 'one-of' parameters exist

### PR DESCRIPTION
**Pull request by Rob-Johnson**
be stricter about the 'one-of' constraint, currently there is only a check for _atleast_ one of

### CODE REVIEW

**Comment by solarkennedy** [comment]
This looks ok to me. Are there _any_ fields that you can have multiples of anyway?

**Comment by Rob-Johnson** [comment]
I don't get what you mean? The fields defined in `ChronosJob.one_of` are mutually exclusive - before this change, the validation only checked that **atleast** one of those fields was defined, rather than **exactly** one.

**Comment by solarkennedy** [comment]
Ah, now I understand.

**Comment by Rob-Johnson** [comment]
woops, I forgot about this. merging.

**Pull request merged**
