### PR TITLE
Allow a list of servers to be passed in to the client

### PR DESCRIPTION
**Pull request by keshavdv**
Adds support to pass in a list of Chronos servers that will be tried in order (to mimic the marathon-python client). Also adds some custom exception classes so that it's easier to try-catch specific things.

Also fixes issue #2.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Ooo this is good stuff, very similar to the marathon client library. Nice.

**Comment by keshavdv** [comment]
This probably constitutes a breaking API change with the rename of the hostname -> servers kwarg

**Comment by keshavdv** [comment]
Merges in changes from #9 to prevent Github's auto merge from breaking the code.

**Comment by Rob-Johnson** [comment]
Thanks Keshav. @asher it'd be great if we could get this merged.

**Comment by asher** [comment]
@keshavdv would you mind updating the README.md to show an example of passing multiple servers, as in marathon-python/README.md? thanks!

**Comment by keshavdv** [comment]
Done and merged master to fix the conflicts.

**Pull request merged**
