### PR TITLE
Generalize auth token

### PR DESCRIPTION
**Pull request by hylandm**
These contains the improvements that were asked for in [cantenesse's pr](https://github.com/asher/chronos-python/pull/29). I was unable to figure out how to add a test case though, however I tested this throughly locally (adding a token to auth, adding a bad token, ensuring headers persist with the object.)

### CODE REVIEW

**Comment by Rob-Johnson** [comment]
thanks for following up- can you remove the version commit by rebasing? it's out of order atm. I'll merge and release once you've done that.

**Comment by Rob-Johnson** [comment]
sorry, can you remove the .DS_Store file you've added and release commit entirely? I'll do the release separately once this is merged.

**Comment by hylandm** [comment]
Done. Thanks for collaborating.

**Comment by Rob-Johnson** [comment]
Thankyou!

**Pull request merged**
