### PR TITLE
adds ability to pass in a token for authorization

### PR DESCRIPTION
**Pull request by cantenesse**

### CODE REVIEW

**Comment by hylandm** [comment]
👍

**Comment by Rob-Johnson** [comment]
Thanks for the pr @cantenesse 

I'd like to make this a bit more generic: could you please replace the `token` param you've added with a `extra_headers` parameter?

It'll look something like

```
def connect(...., extra_headers):
    self.extra_headers  = extra_headers

def _call(.., extra_headers=None):
    hdrs = {}
    ....
    if extra_headers:
      hdrs.update(extra_headers) 
```

Then when you call the client, it'll look something like:

```
token_auth = { 'Authorization': 'token=xxxx' }
chronos_client = new ChronosClient(extra_headers=token_auth)
```

Could you please also add some unit tests?

Thanks!

**Comment by cantenesse** [comment]
@Rob-Johnson That all sounds very reasonable.  I'll work on that today.

**Comment by Rob-Johnson** [comment]
closed in favour of #32

**Pull request closed without merging**
